/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_DEVICE_DEVICE_PB_H_INCLUDED
#define PB_DEVICE_DEVICE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _device_SetMaxTemp {
    /* Temperature in tenths of a degree Celsius.
 Examples: 250 means 25.0 C and 155 means 15.5 C.
 Valid range: -32768..32767 (int16). Receivers must reject values outside it. */
    int32_t value;
} device_SetMaxTemp;

typedef struct _device_SetMinTemp {
    /* Temperature in tenths of a degree Celsius.
 Examples: 250 means 25.0 C and 155 means 15.5 C.
 Valid range: -32768..32767 (int16). Receivers must reject values outside it. */
    int32_t value;
} device_SetMinTemp;

typedef struct _device_SetCurrentTime {
    /* Current time in milliseconds. */
    uint64_t value_ms;
} device_SetCurrentTime;

/* A command sent from the phone to the STM32 through the ESP32 BLE/UART
 bridge. Exactly one command must be set. */
typedef struct _device_DeviceCommand {
    pb_size_t which_command;
    union _device_DeviceCommand_command {
        device_SetMaxTemp set_max_temp;
        device_SetMinTemp set_min_temp;
        device_SetCurrentTime set_current_time;
    } command;
} device_DeviceCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define device_DeviceCommand_init_default        {0, {device_SetMaxTemp_init_default}}
#define device_SetMaxTemp_init_default           {0}
#define device_SetMinTemp_init_default           {0}
#define device_SetCurrentTime_init_default       {0}
#define device_DeviceCommand_init_zero           {0, {device_SetMaxTemp_init_zero}}
#define device_SetMaxTemp_init_zero              {0}
#define device_SetMinTemp_init_zero              {0}
#define device_SetCurrentTime_init_zero          {0}

/* Field tags (for use in manual encoding/decoding) */
#define device_SetMaxTemp_value_tag              1
#define device_SetMinTemp_value_tag              1
#define device_SetCurrentTime_value_ms_tag       1
#define device_DeviceCommand_set_max_temp_tag    1
#define device_DeviceCommand_set_min_temp_tag    2
#define device_DeviceCommand_set_current_time_tag 3

/* Struct field encoding specification for nanopb */
#define device_DeviceCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_max_temp,command.set_max_temp),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_min_temp,command.set_min_temp),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_current_time,command.set_current_time),   3)
#define device_DeviceCommand_CALLBACK NULL
#define device_DeviceCommand_DEFAULT NULL
#define device_DeviceCommand_command_set_max_temp_MSGTYPE device_SetMaxTemp
#define device_DeviceCommand_command_set_min_temp_MSGTYPE device_SetMinTemp
#define device_DeviceCommand_command_set_current_time_MSGTYPE device_SetCurrentTime

#define device_SetMaxTemp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   value,             1)
#define device_SetMaxTemp_CALLBACK NULL
#define device_SetMaxTemp_DEFAULT NULL

#define device_SetMinTemp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   value,             1)
#define device_SetMinTemp_CALLBACK NULL
#define device_SetMinTemp_DEFAULT NULL

#define device_SetCurrentTime_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   value_ms,          1)
#define device_SetCurrentTime_CALLBACK NULL
#define device_SetCurrentTime_DEFAULT NULL

extern const pb_msgdesc_t device_DeviceCommand_msg;
extern const pb_msgdesc_t device_SetMaxTemp_msg;
extern const pb_msgdesc_t device_SetMinTemp_msg;
extern const pb_msgdesc_t device_SetCurrentTime_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define device_DeviceCommand_fields &device_DeviceCommand_msg
#define device_SetMaxTemp_fields &device_SetMaxTemp_msg
#define device_SetMinTemp_fields &device_SetMinTemp_msg
#define device_SetCurrentTime_fields &device_SetCurrentTime_msg

/* Maximum encoded size of messages (where known) */
#define DEVICE_DEVICE_PB_H_MAX_SIZE              device_DeviceCommand_size
#define device_DeviceCommand_size                13
#define device_SetCurrentTime_size               11
#define device_SetMaxTemp_size                   6
#define device_SetMinTemp_size                   6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
