/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_DEVICE_DEVICE_PB_H_INCLUDED
#define PB_DEVICE_DEVICE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _device_TemperatureUnit {
    device_TemperatureUnit_TEMPERATURE_UNIT_CELSIUS = 0,
    device_TemperatureUnit_TEMPERATURE_UNIT_FAHRENHEIT = 1
} device_TemperatureUnit;

typedef enum _device_BleConnectionState {
    device_BleConnectionState_BLE_CONNECTION_STATE_DISCONNECTED = 0,
    device_BleConnectionState_BLE_CONNECTION_STATE_CONNECTING = 1,
    device_BleConnectionState_BLE_CONNECTION_STATE_CONNECTED = 2,
    device_BleConnectionState_BLE_CONNECTION_STATE_DISCONNECTING = 3
} device_BleConnectionState;

/* Struct definitions */
typedef struct _device_SetMaxTemp {
    /* Temperature in tenths of a degree Celsius.
 Examples: 250 means 25.0 C and 155 means 15.5 C.
 Valid range: -32768..32767 (int16). Receivers must reject values outside it. */
    int32_t value;
} device_SetMaxTemp;

typedef struct _device_SetMinTemp {
    /* Temperature in tenths of a degree Celsius.
 Examples: 250 means 25.0 C and 155 means 15.5 C.
 Valid range: -32768..32767 (int16). Receivers must reject values outside it. */
    int32_t value;
} device_SetMinTemp;

typedef struct _device_SetMaxHumidity {
    /* Relative humidity in tenths of a percent. Valid range: 0..1000. */
    uint32_t value;
} device_SetMaxHumidity;

typedef struct _device_SetMinHumidity {
    /* Relative humidity in tenths of a percent. Valid range: 0..1000. */
    uint32_t value;
} device_SetMinHumidity;

typedef struct _device_SetCurrentTime {
    /* Current time in milliseconds. */
    uint64_t value_ms;
} device_SetCurrentTime;

typedef struct _device_SetTemperatureUnit {
    device_TemperatureUnit unit;
} device_SetTemperatureUnit;

/* A command sent from a client device to the STM32 through the ESP32 BLE/UART
 bridge. Exactly one command must be set. */
typedef struct _device_DeviceCommand {
    pb_size_t which_command;
    union _device_DeviceCommand_command {
        device_SetMaxTemp set_max_temp;
        device_SetMinTemp set_min_temp;
        device_SetCurrentTime set_current_time;
        device_SetTemperatureUnit set_temperature_unit;
        device_SetMaxHumidity set_max_humidity;
        device_SetMinHumidity set_min_humidity;
    } command;
} device_DeviceCommand;

typedef struct _device_EnvironmentMeasurement {
    /* Temperature in tenths of a degree Celsius. */
    int32_t temperature_tenths_celsius;
    /* Relative humidity in thousandths of a percent. */
    bool has_humidity_milli_percent;
    uint32_t humidity_milli_percent;
} device_EnvironmentMeasurement;

typedef struct _device_EnvironmentLimits {
    /* Configured minimum temperature in tenths of a degree Celsius. */
    int32_t min_temperature_tenths_celsius;
    /* Configured maximum temperature in tenths of a degree Celsius. */
    int32_t max_temperature_tenths_celsius;
    /* Configured minimum relative humidity in tenths of a percent. */
    uint32_t min_humidity_tenths_percent;
    /* Configured maximum relative humidity in tenths of a percent. */
    uint32_t max_humidity_tenths_percent;
} device_EnvironmentLimits;

typedef struct _device_DeviceTelemetry {
    pb_size_t which_data;
    union _device_DeviceTelemetry_data {
        device_EnvironmentMeasurement measurement;
        device_EnvironmentLimits limits;
    } data;
} device_DeviceTelemetry;

/* BLE connection state reported by the ESP32 bridge to the STM32. */
typedef struct _device_BridgeStatus {
    device_BleConnectionState ble_connection_state;
} device_BridgeStatus;

/* Envelope carried by every BLE and framed UART payload. */
typedef struct _device_DeviceMessage {
    pb_size_t which_payload;
    union _device_DeviceMessage_payload {
        device_DeviceCommand command;
        device_DeviceTelemetry telemetry;
        device_BridgeStatus bridge_status;
    } payload;
} device_DeviceMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _device_TemperatureUnit_MIN device_TemperatureUnit_TEMPERATURE_UNIT_CELSIUS
#define _device_TemperatureUnit_MAX device_TemperatureUnit_TEMPERATURE_UNIT_FAHRENHEIT
#define _device_TemperatureUnit_ARRAYSIZE ((device_TemperatureUnit)(device_TemperatureUnit_TEMPERATURE_UNIT_FAHRENHEIT+1))

#define _device_BleConnectionState_MIN device_BleConnectionState_BLE_CONNECTION_STATE_DISCONNECTED
#define _device_BleConnectionState_MAX device_BleConnectionState_BLE_CONNECTION_STATE_DISCONNECTING
#define _device_BleConnectionState_ARRAYSIZE ((device_BleConnectionState)(device_BleConnectionState_BLE_CONNECTION_STATE_DISCONNECTING+1))








#define device_SetTemperatureUnit_unit_ENUMTYPE device_TemperatureUnit




#define device_BridgeStatus_ble_connection_state_ENUMTYPE device_BleConnectionState


/* Initializer values for message structs */
#define device_DeviceMessage_init_default        {0, {device_DeviceCommand_init_default}}
#define device_DeviceCommand_init_default        {0, {device_SetMaxTemp_init_default}}
#define device_SetMaxTemp_init_default           {0}
#define device_SetMinTemp_init_default           {0}
#define device_SetMaxHumidity_init_default       {0}
#define device_SetMinHumidity_init_default       {0}
#define device_SetCurrentTime_init_default       {0}
#define device_SetTemperatureUnit_init_default   {_device_TemperatureUnit_MIN}
#define device_DeviceTelemetry_init_default      {0, {device_EnvironmentMeasurement_init_default}}
#define device_EnvironmentMeasurement_init_default {0, false, 0}
#define device_EnvironmentLimits_init_default    {0, 0, 0, 0}
#define device_BridgeStatus_init_default         {_device_BleConnectionState_MIN}
#define device_DeviceMessage_init_zero           {0, {device_DeviceCommand_init_zero}}
#define device_DeviceCommand_init_zero           {0, {device_SetMaxTemp_init_zero}}
#define device_SetMaxTemp_init_zero              {0}
#define device_SetMinTemp_init_zero              {0}
#define device_SetMaxHumidity_init_zero          {0}
#define device_SetMinHumidity_init_zero          {0}
#define device_SetCurrentTime_init_zero          {0}
#define device_SetTemperatureUnit_init_zero      {_device_TemperatureUnit_MIN}
#define device_DeviceTelemetry_init_zero         {0, {device_EnvironmentMeasurement_init_zero}}
#define device_EnvironmentMeasurement_init_zero  {0, false, 0}
#define device_EnvironmentLimits_init_zero       {0, 0, 0, 0}
#define device_BridgeStatus_init_zero            {_device_BleConnectionState_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define device_SetMaxTemp_value_tag              1
#define device_SetMinTemp_value_tag              1
#define device_SetMaxHumidity_value_tag          1
#define device_SetMinHumidity_value_tag          1
#define device_SetCurrentTime_value_ms_tag       1
#define device_SetTemperatureUnit_unit_tag       1
#define device_DeviceCommand_set_max_temp_tag    1
#define device_DeviceCommand_set_min_temp_tag    2
#define device_DeviceCommand_set_current_time_tag 3
#define device_DeviceCommand_set_temperature_unit_tag 4
#define device_DeviceCommand_set_max_humidity_tag 5
#define device_DeviceCommand_set_min_humidity_tag 6
#define device_EnvironmentMeasurement_temperature_tenths_celsius_tag 1
#define device_EnvironmentMeasurement_humidity_milli_percent_tag 2
#define device_EnvironmentLimits_min_temperature_tenths_celsius_tag 1
#define device_EnvironmentLimits_max_temperature_tenths_celsius_tag 2
#define device_EnvironmentLimits_min_humidity_tenths_percent_tag 3
#define device_EnvironmentLimits_max_humidity_tenths_percent_tag 4
#define device_DeviceTelemetry_measurement_tag   1
#define device_DeviceTelemetry_limits_tag        2
#define device_BridgeStatus_ble_connection_state_tag 1
#define device_DeviceMessage_command_tag         1
#define device_DeviceMessage_telemetry_tag       2
#define device_DeviceMessage_bridge_status_tag   3

/* Struct field encoding specification for nanopb */
#define device_DeviceMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,command,payload.command),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,telemetry,payload.telemetry),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,bridge_status,payload.bridge_status),   3)
#define device_DeviceMessage_CALLBACK NULL
#define device_DeviceMessage_DEFAULT NULL
#define device_DeviceMessage_payload_command_MSGTYPE device_DeviceCommand
#define device_DeviceMessage_payload_telemetry_MSGTYPE device_DeviceTelemetry
#define device_DeviceMessage_payload_bridge_status_MSGTYPE device_BridgeStatus

#define device_DeviceCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_max_temp,command.set_max_temp),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_min_temp,command.set_min_temp),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_current_time,command.set_current_time),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_temperature_unit,command.set_temperature_unit),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_max_humidity,command.set_max_humidity),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_min_humidity,command.set_min_humidity),   6)
#define device_DeviceCommand_CALLBACK NULL
#define device_DeviceCommand_DEFAULT NULL
#define device_DeviceCommand_command_set_max_temp_MSGTYPE device_SetMaxTemp
#define device_DeviceCommand_command_set_min_temp_MSGTYPE device_SetMinTemp
#define device_DeviceCommand_command_set_current_time_MSGTYPE device_SetCurrentTime
#define device_DeviceCommand_command_set_temperature_unit_MSGTYPE device_SetTemperatureUnit
#define device_DeviceCommand_command_set_max_humidity_MSGTYPE device_SetMaxHumidity
#define device_DeviceCommand_command_set_min_humidity_MSGTYPE device_SetMinHumidity

#define device_SetMaxTemp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   value,             1)
#define device_SetMaxTemp_CALLBACK NULL
#define device_SetMaxTemp_DEFAULT NULL

#define device_SetMinTemp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   value,             1)
#define device_SetMinTemp_CALLBACK NULL
#define device_SetMinTemp_DEFAULT NULL

#define device_SetMaxHumidity_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define device_SetMaxHumidity_CALLBACK NULL
#define device_SetMaxHumidity_DEFAULT NULL

#define device_SetMinHumidity_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define device_SetMinHumidity_CALLBACK NULL
#define device_SetMinHumidity_DEFAULT NULL

#define device_SetCurrentTime_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   value_ms,          1)
#define device_SetCurrentTime_CALLBACK NULL
#define device_SetCurrentTime_DEFAULT NULL

#define device_SetTemperatureUnit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    unit,              1)
#define device_SetTemperatureUnit_CALLBACK NULL
#define device_SetTemperatureUnit_DEFAULT NULL

#define device_DeviceTelemetry_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,measurement,data.measurement),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,limits,data.limits),   2)
#define device_DeviceTelemetry_CALLBACK NULL
#define device_DeviceTelemetry_DEFAULT NULL
#define device_DeviceTelemetry_data_measurement_MSGTYPE device_EnvironmentMeasurement
#define device_DeviceTelemetry_data_limits_MSGTYPE device_EnvironmentLimits

#define device_EnvironmentMeasurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   temperature_tenths_celsius,   1) \
X(a, STATIC,   OPTIONAL, UINT32,   humidity_milli_percent,   2)
#define device_EnvironmentMeasurement_CALLBACK NULL
#define device_EnvironmentMeasurement_DEFAULT NULL

#define device_EnvironmentLimits_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   min_temperature_tenths_celsius,   1) \
X(a, STATIC,   SINGULAR, SINT32,   max_temperature_tenths_celsius,   2) \
X(a, STATIC,   SINGULAR, UINT32,   min_humidity_tenths_percent,   3) \
X(a, STATIC,   SINGULAR, UINT32,   max_humidity_tenths_percent,   4)
#define device_EnvironmentLimits_CALLBACK NULL
#define device_EnvironmentLimits_DEFAULT NULL

#define device_BridgeStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    ble_connection_state,   1)
#define device_BridgeStatus_CALLBACK NULL
#define device_BridgeStatus_DEFAULT NULL

extern const pb_msgdesc_t device_DeviceMessage_msg;
extern const pb_msgdesc_t device_DeviceCommand_msg;
extern const pb_msgdesc_t device_SetMaxTemp_msg;
extern const pb_msgdesc_t device_SetMinTemp_msg;
extern const pb_msgdesc_t device_SetMaxHumidity_msg;
extern const pb_msgdesc_t device_SetMinHumidity_msg;
extern const pb_msgdesc_t device_SetCurrentTime_msg;
extern const pb_msgdesc_t device_SetTemperatureUnit_msg;
extern const pb_msgdesc_t device_DeviceTelemetry_msg;
extern const pb_msgdesc_t device_EnvironmentMeasurement_msg;
extern const pb_msgdesc_t device_EnvironmentLimits_msg;
extern const pb_msgdesc_t device_BridgeStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define device_DeviceMessage_fields &device_DeviceMessage_msg
#define device_DeviceCommand_fields &device_DeviceCommand_msg
#define device_SetMaxTemp_fields &device_SetMaxTemp_msg
#define device_SetMinTemp_fields &device_SetMinTemp_msg
#define device_SetMaxHumidity_fields &device_SetMaxHumidity_msg
#define device_SetMinHumidity_fields &device_SetMinHumidity_msg
#define device_SetCurrentTime_fields &device_SetCurrentTime_msg
#define device_SetTemperatureUnit_fields &device_SetTemperatureUnit_msg
#define device_DeviceTelemetry_fields &device_DeviceTelemetry_msg
#define device_EnvironmentMeasurement_fields &device_EnvironmentMeasurement_msg
#define device_EnvironmentLimits_fields &device_EnvironmentLimits_msg
#define device_BridgeStatus_fields &device_BridgeStatus_msg

/* Maximum encoded size of messages (where known) */
#define DEVICE_DEVICE_PB_H_MAX_SIZE              device_DeviceMessage_size
#define device_BridgeStatus_size                 2
#define device_DeviceCommand_size                13
#define device_DeviceMessage_size                28
#define device_DeviceTelemetry_size              26
#define device_EnvironmentLimits_size            24
#define device_EnvironmentMeasurement_size       12
#define device_SetCurrentTime_size               11
#define device_SetMaxHumidity_size               6
#define device_SetMaxTemp_size                   6
#define device_SetMinHumidity_size               6
#define device_SetMinTemp_size                   6
#define device_SetTemperatureUnit_size           2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
