/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "device.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(device_DeviceCommand, device_DeviceCommand, AUTO)


PB_BIND(device_SetMaxTemp, device_SetMaxTemp, AUTO)


PB_BIND(device_SetMinTemp, device_SetMinTemp, AUTO)


PB_BIND(device_SetMaxHumidity, device_SetMaxHumidity, AUTO)


PB_BIND(device_SetMinHumidity, device_SetMinHumidity, AUTO)


PB_BIND(device_SetCurrentTime, device_SetCurrentTime, AUTO)


PB_BIND(device_DeviceTelemetry, device_DeviceTelemetry, AUTO)



