#ifndef INC_COMMAND_RECEIVER_DEVICE_TYPES_H_
#define INC_COMMAND_RECEIVER_DEVICE_TYPES_H_

typedef enum
{
	BLE_CONNECTION_STATE_DISCONNECTED = 0,
	BLE_CONNECTION_STATE_CONNECTING,
	BLE_CONNECTION_STATE_CONNECTED,
	BLE_CONNECTION_STATE_DISCONNECTING,
} ble_connection_state_t;

typedef enum
{
	DEVICE_TEMPERATURE_UNIT_CELSIUS = 0,
	DEVICE_TEMPERATURE_UNIT_FAHRENHEIT,
} device_temperature_unit_t;

#endif /* INC_COMMAND_RECEIVER_DEVICE_TYPES_H_ */
